- docs/AboutUs.md
> Update image name reference for matthewken19

- src/main/java/educonnect/commons/util/StringUtil.java
- src/main/java/educonnect/logic/parser/FindCommandParser.java
- src/main/java/educonnect/model/student/NameContainsKeywordsPredicate.java
- src/test/java/educonnect/logic/commands/CommandTestUtil.java
- src/test/java/educonnect/logic/commands/FindCommandTest.java
- src/test/java/educonnect/logic/parser/AddressBookParserTest.java
- src/test/java/educonnect/logic/parser/FindCommandParserTest.java
- src/test/java/educonnect/model/ModelManagerTest.java
- src/test/java/educonnect/model/student/NameContainsKeywordsPredicateTest.java
fixes #50 
find john -> John Doe, Johnson-Darmer, John Cram
> Find fuzzy command

- src/main/resources/view/CommandBox.fxml
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/ResultDisplay.fxml
> Update styles for result display section

- src/main/java/educonnect/ui/StudentCard.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/Extensions.css
- src/main/resources/view/HelpWindow.css
- src/main/resources/view/StudentListCard.fxml
> Change display details of students and overall layout style

- src/main/resources/view/Extensions.css
> Fix empty cell color bug

- src/main/java/educonnect/logic/Messages.java
- src/main/java/educonnect/logic/commands/DeleteCommand.java
- src/main/java/educonnect/logic/parser/DeleteCommandParser.java
- src/main/java/educonnect/model/AddressBook.java
- src/main/java/educonnect/model/Model.java
- src/main/java/educonnect/model/ModelManager.java
- src/main/java/educonnect/model/student/Student.java
- src/main/java/educonnect/model/student/UniqueStudentList.java
- src/test/java/educonnect/logic/LogicManagerTest.java
- src/test/java/educonnect/logic/commands/AddCommandIntegrationTest.java
- src/test/java/educonnect/logic/commands/AddCommandTest.java
- src/test/java/educonnect/logic/commands/CommandTestUtil.java
- src/test/java/educonnect/logic/commands/DeleteCommandTest.java
- src/test/java/educonnect/logic/parser/AddressBookParserTest.java
- src/test/java/educonnect/logic/parser/DeleteCommandParserTest.java
- src/test/java/educonnect/testutil/TypicalStudents.java
fixes #46 
Unique identifier:
Student Id
Email
Telegram Handle
> Delete by unique identifier

- docs/UserGuide.md
> Update delete command in UserGuide

- src/main/java/educonnect/model/util/SampleDataUtil.java
> Bug fix for SampleDataUtil typo

- docs/diagrams/ArchitectureSequenceDiagram.puml
Update UML diagram to reflect edit command instead of delete command.
- ArchitectureSequenceDiagram.puml
> Update UML architecture sequence diagram

- docs/DeveloperGuide.md
- docs/diagrams/BetterModelClassDiagram.puml
- docs/diagrams/ModelClassDiagram.puml
Part of #88 
- (updated to include timetable and link)
- (updated to include timetable and link)
> Update ModelClassDiagram.puml and BetterModelClassDiagram.puml

- docs/diagrams/FindSequenceDiagram.puml
> Add FindSequenceDiagram.puml

- src/main/java/educonnect/model/student/Tag.java
> Update tag validation regex to accept space bar

- docs/UserGuide.md
> Update details in UserGuide.md

- build.gradle
- src/main/java/educonnect/MainApp.java
Update version number to v1.2 and tagged for release
> Update buid.gradle and version numbers

- build.gradle
- src/main/java/educonnect/logic/commands/DeleteCommand.java
- src/main/java/educonnect/logic/parser/DeleteCommandParser.java
> Enable assertions and improve coding readability for delete

- docs/DeveloperGuide.md
- The bug was due to the link to the deleted png files in DG
- We now use html for all puml images instead of manually saved png files
> Fix DG image bug

- docs/DeveloperGuide.md
> Update DG for Timetable feature

- docs/DeveloperGuide.md
- docs/diagrams/StudentClassDiagram.puml
> Update DG on student link

- docs/UserGuide.md
> Remove Link Command from UG, fix typos

- docs/DeveloperGuide.md
- docs/diagrams/FindingAvailableSlotsSequenceDiagram.puml
Includes:
* FindingAvailableSlotsSequenceDiagram.puml
Resolves #130
> Update DG for Timetable and finding slots feature

- .gitignore
- .vscode/settings.json
- src/main/java/educonnect/logic/Messages.java
- src/main/java/educonnect/logic/commands/AddCommand.java
- src/main/java/educonnect/logic/commands/CopyCommand.java
- src/main/java/educonnect/logic/commands/ExitCommand.java
- src/main/java/educonnect/logic/commands/ListCommand.java
- src/main/java/educonnect/logic/parser/AddCommandParser.java
- src/main/java/educonnect/logic/parser/AddressBookParser.java
- src/main/java/educonnect/logic/parser/ArgumentMultimap.java
- src/main/java/educonnect/logic/parser/CopyCommandParser.java
- src/main/java/educonnect/logic/parser/FindCommandParser.java
- src/main/java/educonnect/model/student/predicates/TagContainsKeywordsPredicate.java
- src/main/java/educonnect/model/student/timetable/Day.java
- src/main/java/educonnect/model/student/timetable/Period.java
- src/main/java/educonnect/ui/MainWindow.java
- src/main/java/educonnect/ui/StudentListPanel.java
- src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
- src/test/java/educonnect/logic/commands/CopyCommandTest.java
- src/test/java/educonnect/logic/commands/DeleteCommandTest.java
- src/test/java/educonnect/logic/commands/EditCommandTest.java
- src/test/java/educonnect/logic/commands/EditStudentDescriptorTest.java
- src/test/java/educonnect/logic/parser/AddCommandParserTest.java
- src/test/java/educonnect/logic/parser/CopyCommandParserTest.java
- src/test/java/educonnect/storage/JsonAdaptedStudentTest.java
- src/test/java/educonnect/testutil/TypicalStudents.java
command word is: `copy`
* copies emails to clipboard in the form of: `email1, email2, email3`
* filter by optional tags
* shows emails copied in the StudentListPanel
* does not empty clipboard if no students were found to copy
resolves #120
> Add copy command

- docs/UserGuide.md
> Remove delete function using index in userguide

- src/main/java/educonnect/MainApp.java
- src/main/java/educonnect/ui/MainWindow.java
- Update logging messages
- Disable saving adjusted window size for resetting to default size each time user launches the app
> Update UI settings for v1.3b

- src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
- src/test/java/educonnect/logic/commands/CopyCommandTest.java
> Fix multiple emails copied test case

- src/main/java/educonnect/logic/commands/AddCommand.java
- src/main/java/educonnect/logic/commands/DeleteCommand.java
- src/main/java/educonnect/logic/commands/EditCommand.java
- src/main/java/educonnect/logic/commands/FindCommand.java
- src/main/java/educonnect/logic/parser/AddCommandParser.java
- src/main/java/educonnect/logic/parser/DeleteCommandParser.java
- src/main/java/educonnect/logic/parser/EditCommandParser.java
fixes #146 
fixes #151 
fixes #153 
fixes #154
> Add clearer command message usages, no duplicate prefixes for delete and make code readable for msg usage.

- docs/UserGuide.md
> Update userguide for optional prefixes

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/diagrams/BetterModelClassDiagram.puml
Resolves #170 
* Add acknowledgements
* Remove non-relevant user stories
* Remove non-relevant use case
* Update Class Diagram to reflect correct multiplicity for Timetable package
> Update and fix typos in UG and DG

- src/main/java/educonnect/logic/parser/AddCommandParser.java
- src/main/java/educonnect/logic/parser/EditCommandParser.java
> Fix first day not captured for timetable-related commands

- src/main/java/educonnect/logic/commands/SlotsCommand.java
- src/main/java/educonnect/model/student/timetable/Period.java
> Improves grammar of messages for Timetable and SlotsCommand

- src/main/java/educonnect/logic/parser/ParserUtil.java
> Fix InvalidPeriodException not being thrown to ParseException for display

- src/main/java/educonnect/logic/parser/AddCommandParser.java
- src/main/java/educonnect/logic/parser/EditCommandParser.java
- src/test/java/educonnect/logic/parser/AddCommandParserTest.java
Resolves #206 
* Fix the issue in AddCommandParser
* Fix the issue in EditCommandParser
*
> Fix unable to parse capitalized day prefixes

- docs/UserGuide.md
- src/main/java/educonnect/logic/commands/EditCommand.java
fixes #177
fixes #179
fixes #183 
fixes #190 
fixes #192
fixes #195 
fixes #207
fixes #243
10/04/24
fixes #173
> Update ug ped

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/educonnect/logic/parser/ParserUtil.java
Fixes #198 
Fixes #229 
Resolves #247 
Resolves #246
> Fix timetable and slot duration documentation bug and add appendix to DG

- docs/UserGuide.md
- src/main/java/educonnect/logic/commands/SlotsCommand.java
- src/main/java/educonnect/model/student/timetable/exceptions/OverlapPeriodException.java
fixes #185 
fixes #228
fixes #193 
fixes #200 
fixes #203 
fixes #205 
fixes #207
fixes #219
fixes #222
fixes #234 
fixes #242
> Add clarification for slots and corrected wrong timing

- src/main/java/educonnect/logic/Messages.java
- src/main/java/educonnect/logic/commands/FindCommand.java
- src/main/java/educonnect/logic/parser/FindCommandParser.java
- src/main/java/educonnect/model/student/predicates/EmailContainsKeywordsPredicate.java
- src/main/java/educonnect/model/student/predicates/IdContainsKeywordsPredicate.java
- src/main/java/educonnect/model/student/predicates/NameContainsKeywordsPredicate.java
- src/main/java/educonnect/model/student/predicates/TagContainsKeywordsPredicate.java
- src/main/java/educonnect/model/student/predicates/TelegramContainsKeywordsPredicate.java
- src/test/java/educonnect/logic/commands/CommandTestUtil.java
- src/test/java/educonnect/logic/parser/FindCommandParserTest.java
> Fix empty argument error for find command

- src/main/java/educonnect/logic/parser/EditCommandParser.java
- src/main/java/educonnect/model/student/predicates/EmailMatchesKeywordsPredicate.java
- src/main/java/educonnect/model/student/predicates/IdMatchesKeywordsPredicate.java
- src/main/java/educonnect/model/student/predicates/TelegramMatchesKeywordsPredicate.java
- src/test/java/educonnect/logic/parser/EditCommandParserTest.java
Fix #180 
- Add predicates for exact matching
- Update test files
> Fix edit command unique identifier bug

- docs/UserGuide.md
> Add Known Issues to UG

- docs/UserGuide.md
> Update wrong link in UG

- docs/UserGuide.md
- src/main/java/educonnect/logic/parser/ParserUtil.java
- src/main/java/educonnect/model/student/timetable/Timetable.java
> Branch update wrong timetable prefix error message
